ENDPOINTS:
    IAM: http://iam.seagate.com:9080
    IAM_HTTPS: https://iam.seagate.com:9443
    STS: http://sts.seagate.com:9080
    STS_HTTPS: https://sts.seagate.com:9443

DEFAULT_REGION: us-west2

# SSL section configurations are read only in case of https connection.
SSL:
    CA_CERT_FILE: /etc/ssl/stx-s3-clients/s3/ca.crt
    CHECK_SSL_HOSTNAME: True
    VERIFY_SSL_CERT: True

BOTO:
    ENABLE_LOGGER: True
    # Log level can be DEBUG, CRITICAL, ERROR, WARNING, INFO, NOTSET
    LOG_LEVEL: DEBUG
    LOG_FILE_PATH: /var/log/seagate/auth/s3iamcli.log
