eos_core:                                   # Section for S3 background delete config
   endpoint: "http://127.0.0.1:5000"  # EOS mero client will use the specified host

logconfig:                                  # Section for scheduler & processor loggers.

   # Logging facility for Python https://docs.python.org/3/library/logging.html

   scheduler_logger_name: "object_recovery_scheduler"                                         # Root logger name for scheduler
   processor_logger_name: "object_recovery_processor"                                         # Root logger name for processor
   scheduler_log_file: "/var/log/seagate/s3/s3backgrounddelete/object_recovery_scheduler.log" # Log file path for background delete scheduler
   processor_log_file: "/var/log/seagate/s3/s3backgrounddelete/object_recovery_processor.log" # Log file path for background delete processor
   file_log_level: 10                                                                         # Sets the threshold for above file loggers to level specified. https://docs.python.org/3/library/logging.html#levels 
   console_log_level: 40                                                                      # Sets the threshold for console loggers to level specified. https://docs.python.org/3/library/logging.html#levels 
   log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"                         # Sets the specifed log format https://docs.python.org/3/library/logging.html#logging.Formatter

rabbitmq:                                    # Section for RabbitMQ configs

   # RabbitMQ overview:  https://www.rabbitmq.com/getstarted.html

    username: "admin"                 # Username used to communicate with RabbitMQ
    password: "password"              # Password corresponding to username
    host: "127.0.0.1"                 # Host on which RabbitMQ is runnning
    queue: "s3_delete_obj_job_queue"  # Queue name used in RabbitMQ
    exchange: ""                      # Exchanges control the routing of messages to queues.
    exchange_type: "direct"           # Exchanges type includes direct, fanout, topic exchange, header exchange
    mode: 2                           # Valid values are Non-persistent (1) or persistent (2). persistent ensures that the task_queue queue won't be lost even if RabbitMQ restarts.
    durable: "True"                   # Ensure that RabbitMQ will never lose our queue.
    schedule_interval_secs: 900       # Schedule Interval is time period at which object recovery scheduler will be executed (in seconds)

indexid:

   probable_delete_index_id: "probable_delete_index_id"      # Index id containing list of probable delete object oid.
   object_metadata_index_id: "object_metadata_index_id"      # Index id containing object metadata
