---

- name: Add repository for lustre
  yum_repository:
    name: releases_hermi_lustre
    description: Yum repo for lustre
    baseurl: http://jenkins.mero.colo.seagate.com/share/bigstorage/releases/hermi/last_successful/lustre/repo/
    gpgcheck: no
    priority: 1

- name: Add S3 deps repository
  yum_repository:
    name: releases_hermi_s3server_uploads
    description: Yum repo for S3 server dependencies
    baseurl: http://jenkins.mero.colo.seagate.com/share/bigstorage/releases/hermi/s3server_uploads/
    gpgcheck: no
    priority: 1

- name: Install S3 dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - java-1.8.0-openjdk-headless

- name: Update to latest selinux-policy (required by latest openldap)
  yum: pkg={{item}} state=latest
  with_items:
    - selinux-policy

- name: Install S3 runtime dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - openssl
    - openssl-libs
    - libxml2
    - libyaml
    - yaml-cpp
    - gflags
    - glog

- name: Update to latest selinux-policy (required by latest openldap)
  yum: pkg={{item}} state=latest
  with_items:
    - selinux-policy

# Keep commented for future reference
# - name: Install nginx
#   yum:
#     name: nginx
#     state: present
#
# - name: Setup nginx config
#   copy:
#     src: ./files/nginx/nginx.conf.seagate
#     dest: /etc/nginx/nginx.conf

- name: Install haproxy
  yum:
    name: haproxy
    state: present

- name: Setup haproxy config
  copy:
    src: ./files/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Setup haproxy 503 error code to http file
  copy:
    src: ./files/haproxy/503.http
    dest: /etc/haproxy/errors/

- name: Setup haproxy config to enable logs
  copy:
    src: ./files/haproxy/rsyslog.d/haproxy.conf
    dest: /etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog

- name: Enable http port in selinux
  command: setsebool httpd_can_network_connect on -P
  when: ansible_selinux.status == "enabled"

- name: Install keepalived
  yum:
    name: keepalived
    state: present

- name: Setup keepalived master config (sample, manually updated)
  copy:
    src: ./files/keepalived/keepalived.conf.master
    dest: /etc/keepalived/keepalived.conf.master

- name: Create working directory for S3 server.
  file: path=/var/seagate/s3 state=directory
