---

# Sets up the S3 development environment.
# Prerequisites: common_build_env.yml and jenkins_yum_repos.yml

- name: Install lustre rpms
  when: ansible_os_family != "Redhat"
  yum: pkg={{item}} state=present
  with_items:
    - lustre-client
    - lustre-client-devel
    - kmod-lustre-client

- name: Install patched s3cmd deps
  yum:
    name: python-magic
    state: present

- name: Install patched s3cmd
  yum:
    name: s3cmd
    disablerepo: '*'
    enablerepo: releases_s3server_uploads
    state: present

- name: Install patched log4cxx_eos
  yum:
    name:
      - log4cxx_eos
      - log4cxx_eos-devel
    state: present

- name: Install tools for ST
  yum: pkg={{item}} state=installed
  with_items:
    - ossperf
    - parallel
    - bc
    - coreutils

- name: Configure lnet
  when: ansible_os_family != "Redhat"
  template:
    src: templates/lnet.conf
    dest: /etc/modprobe.d/lnet.conf

- name: Add the lnet module
  modprobe:
    name: lnet
    state: present

- name: Enable modprobe lnet on reboot
  when: ansible_os_family != "Redhat"
  lineinfile:
    path: /etc/modules-load.d/lnet.conf
    line: 'lnet'
    create: yes

- name: Configure lnet
  command: lctl net up

- name: Enable lnet up on reboot
  when: ansible_os_family != "Redhat"
  lineinfile:
    path: /etc/profile
    line: 'lctl net up'

- name: Test lnet
  command: lctl list_nids
