---
- name: Copy s3-deps rpms to configured node
  copy:
    src: files/s3-deps
    dest: /tmp/

- name: Install S3 development build tools
  yum: pkg={{item}} state=installed
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - maven
    - unzip
    - clang
    - cmake
    - zlib-devel

- name: Install S3 development build time dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - openssl
    - openssl-libs
    - openssl-devel
    - libxml2
    - libxml2-devel
    - libyaml
    - libyaml-devel
    - yaml-cpp
    - yaml-cpp-devel
    - gflags
    - gflags-devel
    - glog
    - glog-devel

- name: Install Python and dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - python34
    - python34-pip
    - python34-setuptools
    - python34-dateutil
    - python34-devel
    - python34-yaml
    # - xmltodict
    # - boto3
    # - botocore
    - python34-scripttest

- name: Install python modules to build python34 dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - pytest
    - python-jsonschema
    - python-keyring
    - python-nose
    - python34-nose
    - python-mock
    - python-wheel
    - python2-botocore
    - python2-jmespath
    - python-futures
    - python2-s3transfer
    - python34-mock

- name: Install python modules required by S3 system tests and s3 (iam) auth cli
  yum: pkg={{item}} state=installed
  with_items:
    - /tmp/s3-deps/{{ python34_wheel_rpm }}
    - /tmp/s3-deps/{{ python34_jmespath_rpm }}
    - /tmp/s3-deps/{{ python34_xmltodict_rpm }}
    - /tmp/s3-deps/{{ python34_botocore_rpm }}
    - /tmp/s3-deps/{{ python34_s3transfer_rpm }}
    - /tmp/s3-deps/{{ python34_boto3_rpm }}

- name: Install bazel rpm
  yum:
    name: /tmp/s3-deps/{{ bazel_rpm }}
    state: present

- name: Install gtest and gtest-devel rpm
  yum: pkg={{item}} state=installed
  with_items:
    - /tmp/s3-deps/{{ gtest_rpm }}
    - /tmp/s3-deps/{{ gtest_devel_rpm }}

- name: Install gmock and gmock-devel rpm
  yum: pkg={{item}} state=installed
  with_items:
    - /tmp/s3-deps/{{ gmock_rpm }}
    - /tmp/s3-deps/{{ gmock_devel_rpm }}

- name: Install git_clang_format_rpm rpm
  yum: pkg={{item}} state=installed
  with_items:
    - /tmp/s3-deps/{{ git_clang_format_rpm }}
