---

- name: S3 rpm build setup (Centos 75) (Assumes mero build env is set up)
# Mero build env should be setup and mero and lustre rpms should be installed.
# Clone mero and build using ./autogen.sh && ./configure && make rpms-notests
  hosts: s3devvm
  remote_user: root
  gather_facts: yes
  vars:
    gmock_rpm: gmock-1.7.0-1.el7.centos.x86_64.rpm
    gmock_devel_rpm: gmock-devel-1.7.0-1.el7.centos.x86_64.rpm
    gtest_rpm: gtest-1.7.0-2.el7.centos.x86_64.rpm
    gtest_devel_rpm: gtest-devel-1.7.0-2.el7.centos.x86_64.rpm
    bazel_rpm: bazel-0.11.1-1.el7.centos.x86_64.rpm
    git_clang_format_rpm: git-clang-format-6.0-1.el7.centos.x86_64.rpm
    python34_wheel_rpm: python34-wheel-0.24.0-2.el7.centos.noarch.rpm
    python34_jmespath_rpm: python34-jmespath-0.9.0-1.el7.centos.noarch.rpm
    python34_xmltodict_rpm: python34-xmltodict-0.9.0-1.el7.centos.noarch.rpm
    python34_botocore_rpm: python34-botocore-1.6.0-1.el7.centos.noarch.rpm
    python34_s3transfer_rpm: python34-s3transfer-0.1.10-1.el7.centos.noarch.rpm
    python34_boto3_rpm: python34-boto3-1.4.6-1.el7.centos.noarch.rpm

  tasks:
  - import_tasks: common_build_env.yml
