---

# you may have to `yum install epel-release -y`

- import_playbook: openldap.yml

- name: S3 release node setup (Centos 74)
  hosts: s3releasenode
  remote_user: root
  gather_facts: yes

  tasks:
    - import_tasks: common_runtime.yml

    - name: Add mero repository
      yum_repository:
        name: releases_hermi_mero
        description: Yum repo for mero rpms
        baseurl: http://jenkins.mero.colo.seagate.com/share/bigstorage/releases/hermi/last_successful/mero/repo/
        gpgcheck: no
        priority: 1

    - name: Add halon repository
      yum_repository:
        name: releases_hermi_halon
        description: Yum repo for mero rpms
        baseurl: http://jenkins.mero.colo.seagate.com/share/bigstorage/releases/hermi/last_successful/halon/repo/
        gpgcheck: no
        priority: 1

  handlers:
      - name: restart slapd
        service:
          name: slapd
          state: restarted

      - name: restart rsyslog
        service:
          name: rsyslog
          state: restarted
