---

- import_playbook: openldap.yml

- name: S3 dev vm setup (Centos 75)
  hosts: s3devvm
  remote_user: root
  gather_facts: yes

  tasks:
    - name: Enable epel repo
      yum: pkg={{item}} state=installed
      with_items:
        - epel-release

    - import_tasks: common_build_env.yml
    - import_tasks: common_runtime.yml
    - import_tasks: common_dev_setup.yml

  handlers:
      - name: restart slapd
        service:
          name: slapd
          state: restarted

      - name: restart rsyslog
        service:
          name: rsyslog
          state: restarted
