---

- import_playbook: s3_openldap.yml

- name: S3 dev vm setup (Centos 75)
  hosts: s3devvm
  remote_user: root
  gather_facts: yes
  vars:
    lustre_client_rpm: lustre-client-2.11.0-1.el7.x86_64.rpm
    lustre_client_devel_rpm: lustre-client-devel-2.11.0-1.el7.x86_64.rpm
    kmod_lustre_client_rpm: kmod-lustre-client-2.11.0-1.el7.x86_64.rpm
    gmock_rpm: gmock-1.7.0-1.el7.centos.x86_64.rpm
    gmock_devel_rpm: gmock-devel-1.7.0-1.el7.centos.x86_64.rpm
    gtest_rpm: gtest-1.7.0-2.el7.centos.x86_64.rpm
    gtest_devel_rpm: gtest-devel-1.7.0-2.el7.centos.x86_64.rpm
    bazel_rpm: bazel-0.11.1-1.el7.centos.x86_64.rpm
    git_clang_format_rpm: git-clang-format-6.0-1.el7.centos.x86_64.rpm
    python34_wheel_rpm: python34-wheel-0.24.0-2.el7.centos.noarch.rpm
    python34_jmespath_rpm: python34-jmespath-0.9.0-1.el7.centos.noarch.rpm
    python34_xmltodict_rpm: python34-xmltodict-0.9.0-1.el7.centos.noarch.rpm
    python34_botocore_rpm: python34-botocore-1.6.0-1.el7.centos.noarch.rpm
    python34_s3transfer_rpm: python34-s3transfer-0.1.10-1.el7.centos.noarch.rpm
    python34_boto3_rpm: python34-boto3-1.4.6-1.el7.centos.noarch.rpm
    s3cmd_patched_rpm: s3cmd-1.6.1-1.el7.centos.noarch.rpm
    ossperf_rpm: ossperf-3.0-1.x86_64.rpm

  tasks:
  - import_tasks: s3_common_dev.yml
  - import_tasks: s3_common.yml

  handlers:
      - name: restart nginx
        service:
          name: nginx
          state: restarted

      - name: restart slapd
        service:
          name: slapd
          state: restarted
