---

- name: Elasticsearch setup using rsyslog for S3 audit logging
  hosts: elasticsearch
  remote_user: root
  gather_facts: yes

  tasks:
    - name: Download and install the public signing key for elasticsearch and kibana
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add repository for elasticsearch and kibana
      yum_repository:
        name: elasticsearch-7.x
        description: Elasticsearch repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes
        setype: rpm-md

    - name: Install elasticsearch and kibana
      yum: pkg={{item}} state=installed
      with_items:
        - elasticsearch
        - kibana

    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: restart kibana
      service:
        name: kibana
        state: restarted

    - name: Install rsyslog and elasticsearch dependency packages
      yum: pkg={{item}} state=installed
      with_items:
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/libfastjson4-0.99.8-1.el7.centos.x86_64.rpm
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/libestr-0.1.11-1.el7.x86_64.rpm
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/liblognorm5-2.0.6-1.el7.x86_64.rpm
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-8.40.0-1.el7.x86_64.rpm
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-elasticsearch-8.40.0-1.el7.x86_64.rpm
        - http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-mmjsonparse-8.40.0-1.el7.x86_64.rpm

    - name: Copy rsyslog configuration file for elasticsearch
      copy:
        src: ./files/elasticsearch/elasticsearch.conf
        dest: /etc/rsyslog.d/elasticsearch.conf
        force: yes

    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted

